# GitHub Actions workflow to build and deploy Node.js + Express app to Azure Web App
name: Build and deploy Node.js app to Azure Web App - the-consultant-toolbox

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload dist/ as build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Production
    permissions:
      id-token: write
      contents: read

    steps:
      # 1) Bring down your full repo so package.json & server.js are here
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Pull in the dist/ folder from the build job
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: dist

      # 3) Copy dist/ contents over the repo root
      - name: Merge dist into root
        run: |
          cp -R dist/* .

      # 4) Azure login (using your SPN secrets)
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EF5D61A16984400DABCE03F96037C5A4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_821A370962584F6C816CBA50460C2188 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_520BDFA4DF4D49D7A68EE05EF1421341 }}

      # 5) Configure the App Service to run your Express server on startup
      - name: Configure Startup Command
        run: |
          az webapp config set \
            --resource-group the-consultant-toolbox_group \
            --name the-consultant-toolbox \
            --startup-file "cd /home/site/wwwroot && npm install && npm start"

      # 6) Deploy everything (package.json, server.js, dist/, etc.) into wwwroot
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: the-consultant-toolbox
          slot-name: Production
          package: .

          