# GitHub Actions workflow to build and deploy ONLY dist/ to Azure Web App
name: Build and deploy Node.js app to Azure Web App - the-consultant-toolbox

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload dist/ as build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: dist

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EF5D61A16984400DABCE03F96037C5A4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_821A370962584F6C816CBA50460C2188 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_520BDFA4DF4D49D7A68EE05EF1421341 }}

      - name: Deploy dist/ to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'the-consultant-toolbox'
          slot-name: 'Production'
          package: dist
